#include "exceptions.hpp"

namespace exceptions {

    void test_func() {
        using namespace std;
    }
}
